---
apiVersion: v1
kind: Secret
metadata:
  name: demo01-poi-backend-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/albacoll/demo01-poi-backend-gitops.git
